### ISSUE TITLE
Toaplan2 freezing

### ISSUE THREAD

**Issue by bnice** [atrac17/Toaplan2#10]
@atrac17 Hi, I am one having trouble with Toplan 2 freezing. You mentioned you were unable to reproduce. Let me know what I can send that would help you diagnose the issue.

**Comment by atrac17** [comment]
Video of the issue, core version (shown in the about section), specifics on your setup should suffice. If this was a common problem, It would have been reported by the community. Hopefully I can help.

Thanks.

**Comment by bnice** [comment]
HI,

Well who knew all I need to do was record it. It literally froze and started it again and started to record, now do you think it will freeze? Not in your life. Let's close this for now. I won't open another issue until I have collected the stuff to help reproduce it. 

Thanks for your help,

Ben.
