### ISSUE TITLE
Truxton 2 / Tatsujin Oh Audio Issue

### ISSUE THREAD

**Issue by Disciple1982** [atrac17/Toaplan2#13]
Hello,

Me and others have noticed sound effects missing or extremely quiet in Truxton 2 when enemies explode (especially the larger enemy ships).

Difference can be heard clearly when comparing the audio of the FPGA core to other sources on YouTube.

Example Footage
https://www.youtube.com/watch?v=fSzF02N3zd0&t=55s

FPGA Core Footage
https://www.youtube.com/watch?v=f_1Cg2M0gs4

Just wanted to give you a heads up.

Thanks!

**Comment by atrac17** [comment]
I'll measure PCM off the PCB and apply the appropriate settings in the coming week.  In the interim, there are audio options to lower or raise the volume of the YM2151 and OKI M6295.

**Comment by atrac17** [comment]
Fixed in 30aa56e.
