### ISSUE TITLE
Core freezes

### ISSUE THREAD

**Issue by bnice** [atrac17/Toaplan2#14]
I have a problem where this the games on this cores freeze after a few minutes. Interestingly it runs longer when the mister is first used for the day. I don't have the problems with any other cores. Is there something this core does that is different? Any hints on how to find my problem? I see there is debug in the OSD how do I use this? I thought it might be ram it fine in mem test up to 140 but above this starts getting errors. Any help would appreciated.

**Comment by psomashekar** [comment]
@bnice  Do you use a case for the MiSTer? also, do you have the IO board with fan or without?

**Comment by bnice** [comment]
Hi,
Thanks for getting back to run I have my mister attached a mister multisystem board (includes the equivalent of the io boards and memory ). I have the monster joystick case for it, which is an open case design. I also have a heatsink on the FPGA. I did post on the multi system discord channel about this problem and someone got back told me they it runs fine on these and they even let it run for a while and it continued to run. 

As does seem heat related but the trouble is I don't know if it my de10 board or the multi system board. In either case I live in New Zealand it will cost me a fair bit to send them back... Think of getting a thermal camera on them and having a look. It is really weird only this core is affected, what are its ram speed requirements for this core?

What are all the files related to the this core? I will delete them all in case one has got corrupted. I did see in update all is something applying an offset. I posted on the relevant GitHub https://github.com/BigDendy/ArcadeROMsDB_MiSTer/issues/1  but didn't get a reply. The file is "arcade_offset.json". I see update all has an option to download  attrac17 arcade offsets which I haven't selected as I don't know what offsets are. Could you tell me what these are?

Anyway this comment is far too long post now so I will stop. Just thought I would give a complete dump of what I know. Thanks again for helping.  

Ben

**Comment by bnice** [comment]
Hi,
Okay, I will see when I catch up with my mate and have a look with a thermal camer, thanks for the advice.

Ben
