### ISSUE TITLE
Sprite warping with truxton2_20221225.rbf

### ISSUE THREAD

**Issue by Saroumane** [atrac17/Toaplan2#8]
Hi, I don't know if it is accepted to open issues here, so let's try : 
I do have the "Sprite warping" (past ?) issue with the current truxton2_20221225.rbf core.
Main MiSTer is version 221224.

I tried (with no success) : 
- Reset settings from inside the core
- Cold Reboot before starting the core

If could try previous versions of the core, if needed (and provided)

Anyway, thanks for recreating this legendary PCB !

**Comment by atrac17** [comment]
I have had this reported before and cannot recreate the error. Actual footage of it occurring from the core would be required for me to pinpoint the issue you have described.

**Comment by Saroumane** [comment]
I think I found a way to recreate it at will. (At least on my setup)
Start a game with player 1, as soon as you have control, stick to the right side of the screen, then go up and down while staying on the right-lower part of the screen.
On this video it triggers immediately (timecode : 00:06) : the ship get teleported in the middle of the screen.
https://drop.chapril.org/download/7fb066f34395339d/#AOeofrIhhxS6_SB6SKRRTQ

**Comment by Saroumane** [comment]
Is there anything else I can do ?

**Comment by atrac17** [comment]
Let me know what an SDRAM test says, I cannot replicate this issue on several DE10-nano setups. Nor can anyone I have test replicate it. Let me know how fast your RAM runs. It's hard to address an issue that I cannot replicate. I've only had three people report this, one I know and the issue doesn't exist on a different setup.

**Comment by atrac17** [comment]
@Saroumane how do you play this? What is the controller type? Keyboard interface or gamepad. I've replicated the issue finally.

**Comment by Saroumane** [comment]
Sorry I can't boot my MiSTer for now, I think I have that recurrent SD corruption problem that happens randomly (and maybe when I don't power off the board carefully enough). I need to extract and copy files or reformart the SD card.
But I can tell you I use a Xbox360 joystick and I have probably enabled the "1000 Hz USB polling rate" tweak. Should I revert that ?

**Comment by Saroumane** [comment]
~~Sorry I can't boot my MiSTer for now, I think I have that recurrent SD corruption problem that happens randomly (and maybe when I don't power off the board carefully enough). I need to extract and copy files or reformart the SD card.~~

I use an original Xbox360 (USB wired) gamepad and I had probably enabled the "1000 Hz USB polling rate" tweak on the MiSTer side. I still reproduce the problem after using "Scripts/fast_USB_polling_off.sh" + reboot.

I switched to a wired PS3 Dualshock => I still reproduce the problem.

**Comment by atrac17** [comment]
The bug I am reproducing comes from the keyboard handler, if I play with any controller I cannot reproduce the issue. This may be tied to what you have happen but I don't think it is. I did find a bug from it though. SDRAM is fine, I'll keep trying to replicate your exact issue.

**Comment by atrac17** [comment]
@Saroumane try this build, don't need to do anything but try and replicate. Let me know if this fixes the problem.

[truxton2_20230119.zip](https://github.com/atrac17/Toaplan2/files/10454784/truxton2_20230119.zip)

**Comment by atrac17** [comment]
Completed in [72ff559](https://github.com/atrac17/Toaplan2/commit/72ff559c9355b41e04e88bf432706e117f14b8e6).

**Comment by Saroumane** [comment]
Thank you, I will try this today

**Comment by atrac17** [comment]
> Thank you, I will try this today

You can just use update_all. I've pushed it public. Thanks!

**Comment by Saroumane** [comment]
I can happily report I cannot reporoduce the warping effect with the new build.
I guess it was a matter of having "impossible" inputs (like left + right) registered at the same time by the game ?

Anyway, I'm very impressed by your dedication to this project : fixing rare bugs, preserving advanced features of the PCB (like the fast scrolling) and even improving the game (the stereo mode !). I'm glad I joined your patreon.

**Comment by atrac17** [comment]
Thanks! Glad I solved it. Took me months to replicate it and a day to figure it out. Very happy to know it's solved.
