### ISSUE TITLE
Rolling picture on analog output 

### ISSUE THREAD

**Issue by mabrilG** [atrac17/Toaplan2#9]
Hello @atrac17, I have a Sony consumer television that does not synchronize the image with this core over analog output, display a rolling picture constalely. 
I guess it will be because of the values ​​in the video mode like pixelclock or horizontal front porch. I have previously used games like Snow Bros 2 with groovymame and also other cores than dont give my this problem..

I like to know if the problem is this video mode in my TV or perhaps the parameters are not completely correct in this core.

Thank you for all of your work.

**Comment by atrac17** [comment]
Sync roll has nothing to do with parameters setup in the core. The core is modeled to output the same as hardware. Groovymame doesn't output video the same as the core and can't be used for reference. It's solely an issue with your consumer CRT.
